/**
 * MOY 错误码常量表
 *
 * 命名规则：DOMAIN_REASON，全大写下划线分隔。
 * 新增错误码必须在此登记，禁止散落字符串字面量。
 */
export const ErrorCode = {
  // 通用
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT: 'RATE_LIMIT',

  // 多租户
  TENANT_ISOLATION_VIOLATION: 'TENANT_ISOLATION_VIOLATION',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',

  // 鉴权与权限
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // GEO 业务
  GEO_PROJECT_NOT_FOUND: 'GEO_PROJECT_NOT_FOUND',
  GEO_NO_VERIFIED_RESULTS: 'GEO_NO_VERIFIED_RESULTS',
  GEO_REPORT_NOT_READY: 'GEO_REPORT_NOT_READY',
  GEO_MOCK_DATA_IN_REAL_PROJECT: 'GEO_MOCK_DATA_IN_REAL_PROJECT',

  // Agent / LLM
  LLM_PROVIDER_ERROR: 'LLM_PROVIDER_ERROR',
  LLM_TIMEOUT: 'LLM_TIMEOUT',
  LLM_RATE_LIMIT: 'LLM_RATE_LIMIT',
  AGENT_TASK_FAILED: 'AGENT_TASK_FAILED',
  AGENT_HUMAN_REVIEW_REQUIRED: 'AGENT_HUMAN_REVIEW_REQUIRED',

  // 文件与存储
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',

  // 任务队列
  QUEUE_UNAVAILABLE: 'QUEUE_UNAVAILABLE',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
